name: forth
version: 1.7.1.13

dependencies:
  - base
  - text

library:
  exposed-modules: Forth
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - megaparsec
  - containers

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - forth
      - hspec
