name: alphametics
version: 1.3.0.6

dependencies:
  - base
  - transformers
  - vector
  - containers
  - extra

benchmarks:
  bench:
    main: Benchmark.hs
    source-dirs: bench
    dependencies:
    - alphametics
    - criterion

library:
  exposed-modules:
  - Alphametics
  - Alphametics2
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - alphametics
      - hspec
