name: robot-name
version: 0.1.0.4

dependencies:
  - base
  - transformers

library:
  exposed-modules: Robot
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - containers
  - random

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - robot-name
      - hspec
