name: sieve
version: 1.1.0.5

dependencies:
  - base

library:
  exposed-modules: Sieve
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - vector
  # For Control.Monad.Reader
  - mtl

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - sieve
      - hspec
