name: connect
version: 1.1.0.6

dependencies:
  - base

library:
  exposed-modules: Connect
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - vector
  - containers
  - transformers

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - connect
      - hspec
