name: roman-numerals
version: 1.2.0.6

dependencies:
  - base

library:
  exposed-modules: Roman
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - array

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - roman-numerals
      - hspec
