on: [push]

name: CI

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Install Stack'
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-no-global: true

      - name: Test
        run: .github/run.sh --no-lint

      - name: 'Install HLint'
        uses: haskell-actions/hlint-setup@v2

      - name: 'Run HLint'
        run: hlint --ignore-glob '*/test/*.hs' .

      - name: 'Run Ormolu'
        uses: haskell-actions/run-ormolu@v16
        with:
          pattern: '*/src/*.hs'
