on: [push]

name: CI

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Install Stack'
        uses: haskell/actions/setup@v2
        with:
          enable-stack: true

      - name: 'Install HLint'
        uses: haskell/actions/hlint-setup@v2

      - name: Test
        run: .github/run.sh --no-lint

      - name: Lint
        run: .github/run.sh --no-test
