name: CI

on: [push, workflow_dispatch]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Install Stack'
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true

      - name: 'Install HLint'
        uses: haskell-actions/hlint-setup@v2

      - name: 'Run HLint'
        run: hlint --ignore-glob '*/test/*.hs' .

      - name: 'Check Formatting'
        uses: haskell-actions/run-ormolu@v16
        with:
          pattern: '*/src/*.hs'
          mode: check

      - name: 'Test and Lint'
        run: .github/run.sh --no-lint